// Generated by CoffeeScript 1.10.0
(function() {
  var assert, async, feeds, utils;

  async = require('async');

  assert = require('assert');

  feeds = require('../lib/feeds.json');

  utils = require('../lib/utils.js');

  require('it-each')({
    testPerIteration: true
  });

  describe('Test Active Feeds', function() {
    it('should have feeds', function(done) {
      assert(true, !!feeds.length);
      done();
    });
    it.each(feeds, 'Testing feed for %s', ['id'], function(city, next) {
      if (typeof city.active !== 'undefined' && city.active === false) {
        assert(true, true, 'Skipping Not Active');
        return next();
      } else {
        utils.get(city, function(err, result) {
          if (!result) {
            assert.fail(err, 'result');
          } else {
            assert(true, !!result);
          }
          return next();
        });
      }
    });
  });

  return;

}).call(this);
