// Generated by CoffeeScript 1.10.0
(function() {
  var APIeasy, assert, async, city, code, codes, feeds, i, len, station;

  APIeasy = require("api-easy");

  async = require('async');

  assert = require("assert");

  feeds = require("../lib/feeds.json");

  station = APIeasy.describe("/bikeshare/stations");

  codes = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = feeds.length; i < len; i++) {
      city = feeds[i];
      results.push(city.id);
    }
    return results;
  })();

  station.use("localhost", 8080).setHeader("Content-Type", "application/json").followRedirect(false).discuss('Testing station').get('/bikeshare/stations').expect(200).undiscuss().discuss('Test city lat/long endpoint').get("/bikeshare/stations/37.42/-122.13").expect(200).discuss('Test bad endpoint').get('/bikeshare/spiderman').expect(404);

  for (i = 0, len = codes.length; i < len; i++) {
    code = codes[i];
    station.discuss("testing city " + code).get("/bikeshare/city/" + code).expect(200).undiscuss().discuss("Test city lat/long endpoint " + code).get("/bikeshare/city/" + code + "/37.42/-122.13").expect(200).undiscuss();
  }

  station["export"](module);

}).call(this);
