// Generated by CoffeeScript 1.10.0
(function() {
  var action, app, bikeShare, bodyParser, endpoints, express, http, i, len, middleware, morgan, point, utils, ware;

  bodyParser = require('body-parser');

  express = require('express');

  morgan = require('morgan');

  http = require('http');

  bikeShare = require('./lib/bikeShare.js');

  utils = require('./lib/utils.js');

  endpoints = {
    '/bikeshare/stations': function(req, res) {
      return bikeShare.allStations(req, res);
    },
    '/bikeshare/stations/:lat/:long': function(req, res) {
      return bikeShare.closestStations(req, res);
    },
    '/bikeshare/city/:city': function(req, res) {
      return bikeShare.cityStations(req, res);
    },
    '/bikeshare/city/:city/:lat/:long': function(req, res) {
      return bikeShare.closestStations(req, res);
    }
  };

  middleware = [morgan('dev'), bodyParser.json(), utils.allowCrossDomain, express["static"](__dirname + "/public")];

  app = express();

  app.set("port", process.env.PORT || 8080);

  for (i = 0, len = middleware.length; i < len; i++) {
    ware = middleware[i];
    app.use(ware);
  }

  for (point in endpoints) {
    action = endpoints[point];
    app.get(point, action);
  }

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);
